---
title: "Exercises"
output: html_document
date: "2024-11-06"
---

Exercise 1: Summary of the Paper and Main Findings
Provide a brief summary of the paper you are replicating. Describe the main findings, especially
those related to Study 1.

The authors posit that according to the Homonationalist thesis, support for LGBT+ issues among anti-immigration nativists and right-wing populists is not entirely genuine (organic liberalism thesis) and is instead used strategically (instrumental liberalism thesis) as a tool to justify further exclusion of immigrants, especially Muslims, who are perceived to be more homophobic, than the average western citizen. The rational behind this could be summed up as: "The enemy of my enemy is my friend" or: "I hate them (Muslims) more than I hate the others (LGBT+ people)". 
In order to test this hypothesis, the authors conducted two survey experiments in the UK and Spain. The dependent variable is "Support for LGBT+ inclusive education in school" and was measured by means of survey response on an order randomized scale from 0 to 11, but then for the sake of simplicity were turned into a dichotomous variable for support (0 or 1). 
In the UK, for study 1, the experimental research design randomly assigned 1200 participants into a control group and a treatment group. Those in the control group were exposed to text and pictures of nondenominational people with conventional British names protesting against LGBT+ inclusive education in schools. The treatment group was exposed to the same pictures and text, but the names and pictures were changed to appear Muslim. 
The authors expected that individuals who harbor negative predispositions toward immigration in the treatment group, will display more socially liberal preferences toward LGBT+ education than individuals with comparable anti-immigrant sentiment in the control group.
Indeed, the results showed that (with an average treatment effect of 9.7% points or a 22% increase against the baseline) respondents with an anti-immigrant disposition in the treatment group showed increased support for LGBT+ inclusive education in schools than comparable individuals in the control group. 
On the other hand, among those with positively predisposed toward immigration, treatment exhibits no significant effect below the 5% significance level.
But overall, it can be said, that support for LGBT+ inclusive education is positively correlated with liberal attitudes towards immigrants.
In Study 2, conducted in Spain, chosen because of generally more positive attitude levels towards immigration and LGBT+ issues than in the UK, and a right-wing populist party (VOX), that unlike its counter-part in the UK (UKIP), is not following a homonationalist strategy and is more openly outspoken against LGBT+ issues. They found that regardless of immigration sentiments, treatment resulted in an 10-11% increase in support for LGBT+ inclusive education in schools. However, the effect was stronger among those with anti-immigrant sentiments (21% vs. 14%), when compared against the baseline.
Furthermore, the authors also looked at shifts in citizens pride in "Western Culture". Only among individuals with nativists views could they reasonably demonstrate increased levels of "pride in Western Culture" in the treatment group.

With these findings in mind, the authors argue that the homonationalist thesis is correct and that the increased levels of support for LGBT+ issues among the wider general public in western countries is not entirely genuine, but also in part the result of a strategic move by right-wing populists to deradicalize their image by defining themselves by "who they are not" rather than "who they are". They further speculate that as soon as the political context changes and LGBT+ rights are at stake (but absent of the perceived threat of "immigrants"), the support for LGBT+ issues among right-wing populists will decrease. 

Exercise 2: Data Preparation and Exploration
Use the data file study1_data.csv to begin the replication process. Identify and describe the
experimental variables (i.e., treatment and immigration attitudes) and provide visualizations of their distribution.
Then, select up to four covariates (e.g., gender, age, etc.) and plot their distribution too.
If necessary, clean or transform variables. Document any changes.

```{r pressure, echo=FALSE}
plot(pressure)
```

Exercise 3: Covariate Balance
Check for balance across covariates and report the results in a table and a plot.
Explain your findings. Why would you expect randomization to lead to balance across covariates?



Exercise 4 (additional): Estimate Treatment Effect
This exercise is not mandatory, but it serves only to opt for the maximum grade (6).
Estimate the average effect of the treatment on the outcome variable support conditional on
the pre-treatment immigration attitudes imm_1. For this, use an interaction term in an OLS
regression model. Compare your results to those in the original paper.
Then, repeat this analysis with three iteratively smaller random samples of the treatment 
(n = 200, n = 100, n = 10) and control groups (n = 200, n = 100, n = 10); total N = 400, 200, and 20, respectively. Explain your findings.
Finally, discuss how sample size impacts the results and what this implies about the role of randomization for selection bias.